# Ejercicio 1
lista = list(range(0,101,4))

print(lista)

# Ejercicio 2

lista = [ "river", "futbol","formula1", "basquet","musica"]

Penultimalista = lista[3]

print(Penultimalista)

# Ejercicio 3

Lista = []

Lista.append("river plate")
Lista.append("el mas grande")
Lista.append("del mundo")

print (Lista) 

# Ejercicio 4

animales = ["perro", "gato", "conejo", "pez"]  

animales[1] = "loro"
animales[3] = "oso"

print (animales)

# Ejercicio 5

numeros = [8, 15, 3, 22, 7]

numeros.remove(max(numeros)) # se elimina el numero de mayor valor 
print(numeros)

# Ejercicio 6

Numero = list(range(10,31,5))

print (Numero[0],Numero[1])

# Ejercicio 7 

autos =  ["sedan", "polo", "suran", "gol"]

autos[1] = "amarok"
autos[2]= "nivus"

print (autos)

# Ejercicio 8

dobles = []

dobles.append(10)
dobles.append(20)
dobles.append(30)

print (dobles)

# Ejercicio 9

compras =  [["pan", "leche"], ["arroz", "fideos", "salsa"], ["agua"]] 

compras[2].append("jugo")
compras[1][1]="tallarines"
compras[0].remove("pan")

print (compras) 

# Ejercicio 10

lista_anidadas = [ [15 ], [True], [25.5,57.9,30.6], [False] ]

print(lista_anidadas) 



